#!/usr/bin/env php
<?php

// Installed via composer?
if (file_exists($a = __DIR__.'/../../autoload.php')) {
    require $a;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}

(new Gedex\Ghorg\ApplicationFactory())
    ->createApplication()
    ->run()
;
